PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX schema: <https://schema.org/>

SELECT ?constellation ?description
WHERE {
  ?star schema:name "Alpha Centauri" ;
        dbo:constellation ?constellationResource ;
        schema:description ?description .

  ?constellationResource schema:name ?constellation .
}
