PREFIX schema: <https://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?constellation ?description
WHERE {
  ?star schema:name "Alpha Centauri" ;
        dbo:constellation ?constellationResource ;
        schema:description ?description .

  ?constellationResource schema:name ?constellation .
}
