SELECT ?graph ?name
WHERE {
  GRAPH ?graph {
    ?subject <https://schema.org/name> ?name .
  }
  VALUES ?graph {
    <sparqld:examples/alpha-centauri.yamlld>
    <sparqld:examples/centaurus.md>
    <sparqld:examples/proxima-centauri-b.jsonld>
  }
}
ORDER BY ?graph
