PREFIX dbp: <http://dbpedia.org/property/>
PREFIX schema: <https://schema.org/>

SELECT ?name ?discovered
WHERE {
  GRAPH ?graph {
    ?body schema:name ?name .
    OPTIONAL { ?body dbp:discovered ?discovered }
  }
  FILTER(STRSTARTS(STR(?graph), "sparqld:examples/"))
}
ORDER BY ?name
