PREFIX schema: <https://schema.org/>

SELECT ?name
WHERE {
  GRAPH ?graph {
    ?subject schema:name ?name .
  }
  FILTER(STRSTARTS(STR(?graph), "sparqld:examples/"))
}
ORDER BY ?name
LIMIT 2
OFFSET 1
